[project]
name = "opensignal-tools"
version = "0.1.0"
description = "Script(s) for processing plux opensignal data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas==2.2.3",
    "numpy==2.2.5",
    "tabulate==0.9.0",
    "python-osc==1.9.3"
]
